apiVersion: v1
kind: Service
metadata:
  name: fortune-ui-service
  labels:
    name: fortune-ui-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: ui
  selector:
    name: fortune-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: fortune-ui
  name: fortune-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fortune-ui
  template:
    metadata:
      labels:
        name: fortune-ui
    spec:
      containers:
        - image: kathywan/fortune-ui
          name: fortune-ui
          ports:
            - containerPort: 8080