ribbon:
  isSecure: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    restart:
      enabled: true
      
---

spring:
  profiles: pact

ribbon:
  eureka:
    enabled: false


fortunes:
  ribbon:
    listOfServers: localhost:8080

  