server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true   # added this for k8s
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/