spring:
  jpa:
#    database: MYSQL
    hibernate:
      ddl-auto: create-drop
#  datasource:
#    url: jdbc:mysql://fortune-mysql:3306/fortunesdb

ribbon:
  IsSecure: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        cloud:
          kubernetes:
            config: DEBUG
    io:
      fabric8:
        kubernetes:
          client: DEBUG