spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create-drop
  cloud:
    kubernetes:
      discovery:
        enabled: true
      secrets:
        name: db-secret
      reload:
        enabled: true
      config:
        name: spring-boot-bootstrap
        namespace: default

ribbon:
  IsSecure: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

