apiVersion: v1
kind: Service
metadata:
  name: fortunes
  labels:
    name: fortune-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: fortune-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: fortune-service
  name: fortune-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fortune-service
  template:
    metadata:
      labels:
        name: fortune-service
    spec:
      serviceAccountName: default
      containers:
        - image: kathywan/fortune-service
          name: fortune-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_JPA_DATABASE
              value: MYSQL
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://fortune-mysql:3306/fortunesdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
