apiVersion: v1
kind: Service
metadata:
  name: fortunes
  labels:
    name: fortune-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      targetPort: 8080
  selector:
    name: fortune-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: fortune-service
  name: fortune-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fortune-service
  template:
    metadata:
      labels:
        name: fortune-service
    spec:
      serviceAccountName: fortunesacct
      containers:
        - image: kathywan/fortune-service
          name: fortune-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fortunes
data:
  application.yml: |-
    spring:
      profiles: kubernetes
    spring:
      jpa:
        database: MYSQL
      datasource:
        url: jdbc:mysql://fortune-mysql:3306/fortunesdb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortunesacct
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-read-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-read-rolebinding
subjects:
#  - kind: ServiceAccount
#    name: fortunesacct
#    namespace: default
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-read-role
  apiGroup: rbac.authorization.k8s.io
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  name: read-role
#rules:
#  - apiGroups:
#      - ""
#    resources:
#      - endpoints
#      - pods
#      - services
#      - configmaps
#    verbs:
#      - get
#      - list
#      - watch
#
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: read-rolebinding
#subjects:
#  - kind: ServiceAccount
#    name: fortunesacct
#    namespace: default
#  - kind: ServiceAccount
#    name: default
#    namespace: default
#roleRef:
#  kind: Role
#  name: read-role
#  apiGroup: rbac.authorization.k8s.io