apiVersion: v1
kind: ConfigMap
metadata:
  name: fortunes
data:
  application.yml: |-
    spring:
      profiles: kubernetes
    spring:
      jpa:
        database: MYSQL
      datasource:
        url: jdbc:mysql://fortune-mysql:3306/fortunesdb