apiVersion: v1
kind: Service
metadata:
  name: fortunes
  labels:
    name: fortune-service-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      targetPort: 8080
  selector:
    name: fortune-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: fortune-service
  name: fortune-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fortune-service
  template:
    metadata:
      labels:
        name: fortune-service
    spec:
      containers:
        - image: kathywan/fortune-service
          name: fortune-service
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USERNAME
              value: MYSQL_JDBC_URL
            - name: SPRING_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
